name: Rust CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-version: stable

      - name: Run tests on the root project
        run: cargo test --workspace

      - name: Run tests on example crates
        run: |
          for example in examples/*/; do
            if [ -f "$example/Cargo.toml" ]; then
              echo "Running tests for $example"
              cd $example && cargo test && cd -
            fi
          done